---

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 0
  react/prop-types: 0
