---

parser: babel-eslint

env:
  browser: true
  node: true
  
extends:
  - airbnb
  - "plugin:react/recommended"
  - "plugin:import/react"

parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true

rules:
  react/prop-types: 0
