---

extends:
  - airbnb
  - "plugin:react/recommended"

parser: babel-eslint

parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalDecorators: true

env:
  browser: true
  node: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
